version: 2
jobs:
  progate1:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run Lesson1 script
          command: 'python lesson1/script.py'

  progate2:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run Lesson2 script
          command: 'python Lesson2/script.py'

workflows:
  version: 2
  Progate:
    jobs:
      - progate1
      - progate2

