version: 2
jobs:
  progate1:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run test
          command: 'python lesson1/script.py'

workflows:
  version: 2
  Progate:
    jobs:
      - progate1

