executors:
  default:
    docker:
      - image: cimg/python:3.8.2
    working_directory: ~/repo

version: 2.1
jobs:
  progate1:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Lesson1 script
          command: 'python lesson1/script.py'

  progate2:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Lesson2 script
          command: 'python lesson2/script.py'

  progate3:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Lesson3 script
          command: 'python lesson3/script.py'

  progate4:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Lesson4 script
          command: 'python lesson4/script.py'

  progate5:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Lesson5 script
          command: 'python lesson5/script.py'
  
  test_jests:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: jest-junitパッケージを追加
          command: yarn add -dev jest-junit
      - run:
          name: Jestを実行
          command: |
            npx jest --ci --maxWorkers=2 \
            --reporters=default --reporters=jest-junit
          environment: #レポートファイルの出力先を指定
            JEST_JUNIT_OUTPUT_DIR: "reports/jest"
      - store_test_results: #レポートファイルを保存
          path: reports

workflows:
  version: 2
  Progate:
    jobs:
      - progate1
      - progate2
      - progate3
      - progate4
      - progate5
      - test_jests:
          requires:
            - progate5

